package rutrob.task.exceptions;

public record ErrorResponse(int status, String message) {
}
